---
title: Allan Berry
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: allan.berry@gmail.com
description: This is Allan Berry's Personal Website.
baseurl: ''
url: https://allanberry.com
twitter_username: allanberry
github_username: allanberry
markdown: kramdown
plugins:
- jekyll-feed
permalink: "/posts/:slug/"
highlighter: rouge
github:
- metadata
kramdown:
  header_offset: 1
